import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { Categories, Highlights, Navbar, Sidebar } from "../components";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container bg-gray-300 h-60 m-auto">
        <Sidebar />
        <div>
          <Navbar />
          <Categories />
          <Highlights />
        </div>
      </div>
    </>
  );
};

export default Home;
